<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BibliotecaIA.Repositorio\BibliotecaIA.Repositorio.csproj" />
    <ProjectReference Include="..\BibliotecaIA.Dominio\BibliotecaIA.Dominio.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
